# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ~/DockerVM/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  pg:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8888:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
      
  etcd:
    image: docker.io/bitnami/etcd:3.5
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
      
  # nats:
  #   image: nats
  #   restart: always
  #   ports:
  #     - 4222:4222
volumes:
  etcd_data:
    driver: local